In [1]:
import numpy as np

## 创建数组/矩阵

1. 使用np.array()函数，传入可迭代对象
2. 使用np.arange()函数，传入起始值、终止值、步长
3. 使用np.random.rand()函数，传入矩阵的形状，产生随机数矩阵
4. 使用np.zeros()函数，传入矩阵的形状，产生全为0的矩阵
5. 使用np.ones()函数，传入矩阵的形状，产生全为1的矩阵
6. 使用np.eye()函数，传入矩阵的形状，产生单位矩阵

In [4]:
# 使用np.array()函数，传入可迭代对象
np.array([1, 2, 3])

array([1, 2, 3])

In [6]:
np.array(range(3))

array([0, 1, 2])

In [11]:
# 使用astype()方法，转换数据类型
np.array([1, 2, 3]).astype(float)

array([1., 2., 3.])

In [8]:
# 使用np.arange()函数，传入起始值、终止值、步长
np.arange(1, 7, 2)

array([1, 3, 5])

In [12]:
# 使用np.random.rand()函数，传入矩阵的形状
np.random.rand(2, 3)

array([[0.00325812, 0.73336664, 0.16991259],
       [0.28222472, 0.86298956, 0.73370647]])

In [13]:
# 使用np.zeros()函数，传入矩阵的形状
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# 使用np.ones()函数，传入矩阵的形状
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## numpy数组的属性

1. shape：数组的形状
2. size：数组的元素个数
3. dtype：数组的数据类型
4. T：数组的转置
5. ndim：数组的维度

In [21]:
# 创建一个二维数组
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# shape：数组的形状
arr.shape

(2, 3)

In [18]:
# size：数组的元素个数
arr.size

6

In [19]:
# dtype：数组的数据类型
arr.dtype

dtype('int64')

In [20]:
# T：数组的转置
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [51]:
# ndim：数组的维度
arr.ndim

2

In [53]:
# 创建一个三维数组
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [54]:
arr.shape

(2, 2, 2)

In [56]:
arr.ndim

3

## 数组的运算操作

#### 数学运算
1. round()：对数组中的元素进行四舍五入
2. sum()：对数组中的元素求和
3. mean()：对数组中的元素求平均值
4. max()：对数组中的元素求最大值
5. min()：对数组中的元素求最小值

In [35]:
# 创建一个二维数组
arr = np.random.rand(2, 3)
arr

array([[0.53747757, 0.48211386, 0.37615603],
       [0.11373381, 0.49288539, 0.43029566]])

In [36]:
# round()：对数组中的元素进行四舍五入
arr.round(2)

array([[0.54, 0.48, 0.38],
       [0.11, 0.49, 0.43]])

In [37]:
# sum()：对数组中的元素求和
arr.sum()

np.float64(2.4326623184640206)

In [38]:
# mean()：对数组中的元素求平均值
arr.mean()

np.float64(0.40544371974400345)

In [39]:
# max()：对数组中的元素求最大值
arr.max()

np.float64(0.5374775678387022)

In [40]:
# min()：对数组中的元素求最小值
arr.min()

np.float64(0.113733812412799)

### 数组间的运算

1. 加法：数组之间的加法运算
    - 若两个数组的形状相同，则对应位置的元素相加
    - 若两个数组的形状不同，但满足广播机制，则进行广播运算
        - 广播机制：两个数组的形状分别从末尾开始比较，若对应维度的长度相等或其中一个维度的长度为1，则认为满足广播机制
            - 后缘维度：两个数组的维度从末尾开始比较
                - 例如：(3, 4, 5)和(4, 5)满足广播机制
                - 例如：(3, 4, 5)和(5)满足广播机制
                - 例如：(3, 4, 5)和(3, 1, 5)满足广播机制
                - 例如：(3, 4, 5)和(3, 4, 1)满足广播机制
                - 反例：(3, 4, 5)和(3, 5)不满足广播机制
                - 反例：(3, 4, 5)和(4, 3, 5)不满足广播机制
    - 若两个数组的形状不同，且不满足广播机制，则抛出异常
2. 减法：数组之间的减法运算
3. 乘法：数组之间的乘法运算
    - 若两个数组的形状相同，则对应位置的元素相乘
    - 若两个数组的形状不同，但满足广播机制，则进行广播运算
4. 除法：数组之间的除法运算
5. 矩阵乘法：使用np.dot()函数进行矩阵乘法运算
6. 矩阵点乘：使用np.multiply()函数进行矩阵点乘运算
    - 对应位置的元素相乘
    - 若两个数组的形状不同，但满足广播机制，则进行广播运算
7. 矩阵点除：使用np.divide()函数进行矩阵点除运算
8. 矩阵点幂：使用np.power()函数进行矩阵点幂运算
9. 矩阵点余：使用np.mod()函数进行矩阵点余运算
10. 矩阵点商：使用np.divmod()函数进行矩阵点商运算
11. 矩阵点除法取整：使用np.floor_divide()函数进行矩阵点除法取整运算
12. 矩阵点除法取余：使用np.remainder()函数进行矩阵点除法取余运算

### 数组结构运算

1. reshape()：改变数组的形状
2. flatten()：将数组展平为一维数组
3. ravel()：将数组展平为一维数组
4. transpose()：对数组进行转置 或 T

In [45]:
# 创建一个二维数组
arr = (np.random.rand(2, 3)*10).round()
arr

array([[1., 8., 1.],
       [2., 9., 5.]])

In [46]:
# reshape()：改变数组的形状
arr.reshape(3, 2)

array([[1., 8.],
       [1., 2.],
       [9., 5.]])

In [47]:
# flatten()：将数组展平为一维数组
arr.flatten()

array([1., 8., 1., 2., 9., 5.])

In [48]:
# ravel()：将数组展平为一维数组
arr.ravel()

array([1., 8., 1., 2., 9., 5.])

In [49]:
# transpose()：对数组进行转置 或 T
arr.transpose()

array([[1., 2.],
       [8., 9.],
       [1., 5.]])

In [50]:
arr.T

array([[1., 2.],
       [8., 9.],
       [1., 5.]])