In [1]:
import numpy as np

## axis 的概念

axis = 0: 沿着行的方向进行操作，运算的方向是列
axis = 1: 沿着列的方向进行操作，运算的方向是行

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 轴方向是行，实际运算方向是列
a.sum(axis=0)

array([5, 7, 9])

In [4]:
# 轴方向是列，实际运算方向是行
a.sum(axis=1)

array([ 6, 15])

In [5]:
a.reshape(3, 2) # 3行(axis=0)，2列(axis=1)

array([[1, 2],
       [3, 4],
       [5, 6]])

## numpy 的索引和切片

In [16]:
# 一维数组的索引和切片
arr = np.arange(10)
print(arr)
print(arr[3])

[0 1 2 3 4 5 6 7 8 9]
3


In [17]:
arr[3:6]

array([3, 4, 5])

In [18]:
arr[3:6] = 12
arr

array([ 0,  1,  2, 12, 12, 12,  6,  7,  8,  9])

In [19]:
# 二维数组的索引和切片
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr[2]  # 第三行

array([7, 8, 9])

In [22]:
arr[:, 1]  # 第二列

array([2, 5, 8])

In [23]:
arr[1, 1]  # 第二行第二列

np.int64(5)

In [25]:
arr[:2, 1:]  # 前两行，后两列。符合左闭右开原则

array([[2, 3],
       [5, 6]])

In [26]:
arr[[0, 2], 1:]  # 第一行和第三行，后两列

array([[2, 3],
       [8, 9]])

### 布尔型索引

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr < 5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [29]:
arr[arr < 5] = 3
arr

array([[3, 3, 3],
       [3, 5, 6],
       [7, 8, 9]])

### 三元运算符 np.where()

In [30]:
np.where(arr < 5, 0, 1)

array([[0, 0, 0],
       [0, 1, 1],
       [1, 1, 1]])

### clip()方法

clip(a, a_min, a_max, out=None)
将数组中的元素限制在a_min, a_max之间，大于a_max的就使得它等于 a_max，小于a_min,的就使得它等于a_min。

In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.clip(2, 5)

array([[2, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

In [32]:
arr.clip(2, 5, out=arr)

array([[2, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

## 数组的拼接

In [6]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.vstack((a1, a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.hstack((a1, a2))

array([1, 2, 3, 4, 5, 6])

## 行列交换

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[[0, 1]] = arr[[1, 0]]   # 第一行和第三行交换
arr

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [14]:
arr[:, [0, 1]] = arr[:, [1, 0]]  # 第一列和第二列交换
arr

array([[5, 4, 6],
       [2, 1, 3],
       [8, 7, 9]])