In [1]:
import numpy as np

## numpy生成随机数

1. np.rand(d0, d1, ..., dn) 生成一个[0, 1)之间的随机浮点数或N维浮点数组
2. np.randn(d0, d1, ..., dn) 生成一个浮点数或N维浮点数组，取数范围是一个标准正态分布
3. np.randint(low, high, size) 生成一个[low, high)之间的整数或N维整数数组
4. np.random.choice(a, size, replace=True, p) 从a(数组)中生成随机数，size是生成的随机数的个数，replace表示是否可以重复抽取，p是a中每个元素出现的概率
5. np.random.uniform(low, high, size) 生成一个[low, high)之间的随机浮点数或N维浮点数组
6. np.random.normal(loc, scale, size) 生成一个具有正态分布的随机数或N维随机数组
7. np.random.shuffle(a) 将一个数组a打乱
8. np.random.permutation(a) 返回一个打乱的数组，不改变原数组
9. np.random.seed(s) 设置随机数种子，使得每次生成的随机数相同

In [2]:
# 生成一个[0, 1)之间的随机浮点数
np.random.rand()

0.26405459413040167

In [3]:
# 生成一个[0, 1)之间的N维浮点数组
np.random.rand(2, 3)

array([[0.05941915, 0.55690665, 0.60932952],
       [0.02429756, 0.53115713, 0.74037003]])

In [4]:
# 生成一个浮点数或N维浮点数组，取数范围是一个标准正态分布
np.random.randn(2, 3)

array([[ 0.84217292,  1.00697587,  0.27415332],
       [-0.24685128,  0.69159445, -0.36573804]])

In [5]:
# 生成一个[low, high)之间的整数或N维整数数组
np.random.randint(1, 10, (2, 3))

array([[2, 9, 5],
       [7, 3, 3]], dtype=int32)

In [7]:
# 从a(数组)中生成随机数，size是生成的随机数的个数，replace表示是否可以重复抽取，p是a中每个元素出现的概率
np.random.choice([1, 2, 3, 4, 5], 3, replace=False, p=[0.1, 0.1, 0.1, 0.1, 0.6])

array([2, 5, 4])

In [8]:
# 生成一个[low, high)之间的随机浮点数或N维浮点数组
np.random.uniform(1, 10, (2, 3))

array([[8.66485901, 9.28528947, 9.82588502],
       [7.72640665, 1.90397657, 9.07583353]])

In [9]:
# 生成一个具有正态分布的随机数或N维随机数组
np.random.normal(0, 1, (2, 3))

array([[ 0.5260674 , -1.08987443, -0.59485993],
       [-0.44239373,  0.13965202, -0.33179984]])

In [11]:
# 将一个数组a打乱
a = np.arange(10)
np.random.shuffle(a)
a

array([4, 9, 2, 6, 5, 7, 0, 1, 8, 3])

In [12]:
# 返回一个打乱的数组，不改变原数组
a = np.arange(10)
np.random.permutation(a)

array([6, 8, 3, 7, 1, 0, 5, 4, 9, 2])

In [15]:
# 设置随机数种子，使得每次生成的随机数相同
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [16]:
np.random.seed(0)
np.random.rand()

0.5488135039273248